steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Authenticating with GCP..."
        echo $GCP_CREDENTIALS > $HOME/gcp-key.json
        gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
        gcloud config set project $PROJECT_ID

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying to private Compute Engine instance..."
        gcloud compute ssh ubuntu@${_INSTANCE_NAME} --zone=${_ZONE} --command="
          cd /opt/nodejs/spotz-frontend &&
          git pull &&
          cp /opt/nodejs/config/environment.demo /opt/nodejs/spotz-frontend/src/environments/environment.ts &&
          npm install &&
          npm run build
        "

substitutions:
  _INSTANCE_NAME: "your-instance-name"  # Replace with your private instance name
  _ZONE: "us-central1-c"  # Replace with the GCP zone
  _PROJECT_ID: "your-project-id"  # Replace with your GCP project ID

timeout: '1200s'

options:
  logging: NONE  # Disable logging
