timeout: '1200s'

steps:
  # Step 1: Authenticate with GCP using Service Account Key from Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Authenticating with GCP using Secret Manager..."
        # Fetch the service account key from Secret Manager and save it to a file
        gcloud secrets versions access latest --secret=my-service-account-key > /root/gcp-key.json
        gcloud auth activate-service-account --key-file=/root/gcp-key.json
        gcloud config set project ${_PROJECT_ID}

  # Step 2: Transfer Files to Target Instance via Load Balancer
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Copying files to the target instance..."
        gcloud compute scp --recurse ./dist/* ubuntu@${_LB_IP}:/opt/nodejs/spotz-frontend --zone=${_ZONE}

  # Step 3: Execute Deployment Commands on Target Instance
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying application on the target instance..."
        gcloud compute ssh ubuntu@${_LB_IP} --zone=${_ZONE} --command="\
          cd /opt/nodejs/spotz-frontend && \
          git pull && \
          cp /opt/nodejs/config/environment.demo /opt/nodejs/spotz-frontend/src/environments/environment.ts && \
          npm install && \
          npm run build \
        "

substitutions:
  _PROJECT_ID: "lyrical-beach-439615-f1"
  _LB_IP: "34.110.247.40"  # Replace with the Load Balancer's IP
  _ZONE: "us-central1-c"

logsBucket: "spotzbuildlogs"

options:
  logging: GCS_ONLY  # Logs will only be available in Google Cloud Storage
