name: Debug Deployment to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: Authenticate to GCP using Service Account Key
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set GCP Project
        run: |
          gcloud config set project ${{ secrets.PROJECT_ID }}

      - name: Check Firewall Rules
        run: |
          echo "Checking Firewall Rules..."
          gcloud compute firewall-rules list --filter="name=allow-ssh"

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_NAME }} >> ~/.ssh/known_hosts

      - name: Test SSH Connectivity
        run: |
          echo "Testing SSH connection..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_NAME }} << 'EOF'
            echo "SSH connection successful."
            exit 0
          EOF

      - name: Deploy Angular App
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_NAME }} << 'EOF'
            # Ensure git is set to trust the directory
            git config --global --add safe.directory /opt/nodejs/spotz-frontend

            # Navigate to the app directory
            cd /opt/nodejs/spotz-frontend/

            # Pull the latest changes from the main branch
            git pull origin main

            # Replace the environment file
            cp /opt/nodejs/spotz-devops/config/environment.demo /opt/nodejs/spotz-frontend/src/environments/environment.ts

            # Install dependencies and build the app
            npm install
            npm run build

            echo "Deployment completed successfully."
          EOF
