name: Auto Deployment to GCP - Frontend

on:
  push:
    branches:
      - main  # You can modify this branch name as per your requirement

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}  # Ensure this runs for the `main` branch

    steps:
      - name: Authenticate to GCP using Service Account Key
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set GCP Project
        run: |
          gcloud config set project ${{ secrets.PROJECT_ID }}

      - name: Check if SSH Port is Open (Create if not)
        run: |
          # Check if firewall rule exists, and create it if not
          if ! gcloud compute firewall-rules describe allow-ssh --project=${{ secrets.PROJECT_ID }} &>/dev/null; then
            echo "Creating SSH firewall rule..."
            gcloud compute firewall-rules create allow-ssh \
              --allow tcp:22 \
              --description "Allow SSH for deployment" \
              --priority 1000 \
              --direction IN
          else
            echo "SSH firewall rule already exists."
          fi

      - name: Deploy Angular App to Private Instance
        run: |
          # SSH into the instance using gcloud compute and execute the deployment commands
          gcloud compute ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_NAME }} \
            --project=${{ secrets.PROJECT_ID }} \
            --zone=${{ secrets.ZONE }} \
            --command="
              # Add repository to safe list to avoid 'dubious ownership' error
              git config --global --add safe.directory /opt/nodejs/spotz-frontend
              
              # Ensure proper ownership (optional step)
              sudo chown -R $(whoami):$(whoami) /opt/nodejs/spotz-frontend
              
              # Perform the deployment
              cd /opt/nodejs/spotz-frontend/
              git pull origin main
              cp /opt/nodejs/spotz-devops/config/environment.demo /opt/nodejs/spotz-frontend/src/environments/environment.ts
              npm install
              npm run build
              echo 'Deployment completed.'
            "

      - name: Close SSH Port on GCP Firewall (After Deployment)
        run: |
          # Disable SSH port (delete the firewall rule)
          gcloud compute firewall-rules delete allow-ssh --quiet
