name: Auto Deployment to GCP - Frontend

on:
  push:
    branches:
      - main  # You can modify this branch name as per your requirement

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}  # Ensure this runs for the `main` branch

    steps:
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set GCP Project
        run: |
          gcloud config set project ${{ secrets.PROJECT_ID }}

      - name: Deploy Angular App to Private Instance
        run: |
          # Deploy the Angular app via SSH to the GCP VM
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} << EOF
            echo "Starting deployment..."
            cd /opt/nodejs/spotz-frontend/
            git pull origin main
            cp /opt/nodejs/spotz-devops/config/environment.demo /opt/nodejs/spotz-frontend/src/environments/environment.ts
            npm install
            npm run build
            echo "Deployment completed."
          EOF
