name: Auto Deployment to GCP - Frontend

on:
  push:
    branches:
      - main  # You can modify this branch name as per your requirement

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}  # Ensure this runs for the `main` branch

    steps:
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set GCP Project
        run: |
          gcloud config set project ${{ secrets.PROJECT_ID }}

      - name: Open SSH Port on GCP Firewall (Before Deployment)
        run: |
          # Open SSH port temporarily for deployment
          gcloud compute firewall-rules update allow-ssh --allow tcp:22

      - name: Deploy Angular App to Private Instance
        run: |
          # SSH into the instance using the service account
          gcloud compute ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} \
            --project=${{ secrets.PROJECT_ID }} \
            --zone=${{ secrets.ZONE }} \
            --command="cd /opt/nodejs/spotz-frontend/ && git pull origin main && cp /opt/nodejs/spotz-devops/config/environment.demo /opt/nodejs/spotz-frontend/src/environments/environment.ts && npm install && npm run build && echo 'Deployment completed.'"

      - name: Close SSH Port on GCP Firewall (After Deployment)
        run: |
          # Close the SSH port after deployment
          gcloud compute firewall-rules update allow-ssh --remove
