name: Debug Deployment to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: Authenticate to GCP using Service Account Key
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set GCP Project
        run: |
          gcloud config set project ${{ secrets.PROJECT_ID }}

      - name: Deploy Angular App
        run: |
          # SSH into the instance using gcloud compute and execute deployment commands
          gcloud compute ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_NAME }} \
            --project=${{ secrets.PROJECT_ID }} \
            --zone=${{ secrets.ZONE }} \
            --command="
              git config --global --add safe.directory /opt/nodejs/spotz-frontend
              cd /opt/nodejs/spotz-frontend/
              git pull origin main
              cp /opt/nodejs/spotz-devops/config/environment.demo /opt/nodejs/spotz-frontend/src/environments/environment.ts
              npm install
              npm run build
              echo 'Deployment completed.'
            "
