jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_NAME }} >> ~/.ssh/known_hosts

      - name: Deploy to Instance
        run: |
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_NAME }} << 'EOF'
            cd /opt/nodejs/spotz-frontend
            git pull origin main
            npm install
            npm run build
            echo "Deployment completed successfully"
          EOF
