name: Auto Deployment to GCP - Frontend

on:
  push:
    branches:
      - main  # Change this to your branch if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate to GCP using Service Account
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}  # Store the service account key in GitHub Secrets

      - name: Set GCP Project
        run: |
          gcloud config set project ${{ secrets.PROJECT_ID }}

      - name: Deploy Angular App to Compute Instance
        run: |
          gcloud compute ssh ubuntu@test --zone=us-central1-c --command="
            cd /opt/nodejs/spotz-frontend &&
            git pull &&
            cp /opt/nodejs/spotz-devops/config/environment.demo /opt/nodejs/spotz-frontend/spotz-frontend/src/environments/environment.ts &&
            npm install &&
            npm run build
          "
